### ISSUE TITLE
Division of labor with mozilla/telemetry-airflow?

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/python_mozetl#4]
The README says jobs " will be scheduled over our instance of Airflow". Does that mean that once my job is merged I can simply update e.g. [1] with a path such as:

    https://github.com/mozilla/python_etl/airflow/daily_search_rollup.py

or does this repo have more responsibility than that?

[1] https://github.com/mozilla/telemetry-airflow/blob/master/dags/main_summary.py#L59

**Comment by harterrt** [comment]
Thanks for bringing this up, Sam!

You will not be able to schedule the python file directly. Instead, you'll need to schedule a shell script, similar to [how we launch the batch-view jobs](https://github.com/mozilla/telemetry-airflow/blob/master/dags/longitudinal.py#L68). We have an example script [here](https://github.com/mozilla/python_etl/blob/master/scheduling/airflow.sh).

We need the shell script because our clusters use Jupyter as the default python interpreter. All that script does is download the repository and set the default python interpreter. As always, let me know if you have any issues.

I'll make sure to update the documentation with notes on how to do this. Please leave this issue open until I do :).
